# Your docker-compose.yml content here
version: '3.4'

services:
  nginx:
    build: requirements/nginx/

    ports:
      - "5000:443"

    networks :
      - docker-network
    volumes :
      - cm_volume:/var/www/html
    depends_on :
      - wordpress
  wordpress:
    build: requirements/wordpress/

    networks :
      - docker-network
    volumes :
      - cm_volume:/var/www/html

networks:
  docker-network:
    driver: bridge

volumes :
  cm_volume :
    name : wordpress
    driver : local