# Your docker-compose.yml content here
version: '3.4'

services:
  nginx:
    build: requirements/nginx/

    ports:
      - "8080:443"

    networks :
      - docker-network
    depends_on :
      - wordpress
  wordpress:
    build: requirements/wordpress/

    networks :
      - docker-network
networks:
  docker-network:
    driver: bridge