# Your docker-compose.yml content here
version: '3.4'

services:
  nginx:
    container_name: NGINX
    build: requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    networks :
      - docker-network
    volumes :
      - cm_volume:/var/www/html
    depends_on :
      - wordpress

  wordpress:
    init: true
    container_name: wordpress
    build: requirements/wordpress/
    env_file:
      - .env
    networks :
      - docker-network
    volumes :
      - cm_volume:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    init: true
    container_name: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    networks :
      - docker-network
    volumes :
      - db_volume:/var/lib/mysql

networks:
  docker-network:
    driver: bridge

volumes :
  cm_volume :
    name : wordpress
    driver : local
    driver_opts:
        device: /home/aababach/data/wp_data
  db_volume :
    name : mariadb
    driver : local
    driver_opts:
        device: /home/aababach/data/db_data
